{
  "records": {
    "2018-11-05T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-05T00:01:12.659660-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-05T23:26:27.616868-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-05T23:27:05.454250-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-05T23:59:15.448391-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-05T23:59:28.074598-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statslab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-11-06T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-06T00:00:12.185775-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T00:01:16.650730-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T15:24:58.280915-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 195,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T18:09:40.822201-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 154,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T18:10:59.620384-08:00",
        "exc": "Traceback (most recent call last):\n  File \"core/fairylab/fairylab.py\", line 114, in _try\n    response = item(*args, **dict(kwargs, date=date))\n  File \"/home/pi/filefairy/api/registrable/registrable.py\", line 82, in _run\n    return self._run_internal(**kwargs)\n  File \"/home/pi/filefairy/plugin/gameday/gameday.py\", line 125, in _run_internal\n    self._render(**kwargs)\n  File \"/home/pi/filefairy/api/renderable/renderable.py\", line 55, in _render\n    for html, subtitle, tmpl, context in self._render_internal(**kwargs):\n  File \"/home/pi/filefairy/plugin/gameday/gameday.py\", line 113, in _render_internal\n    game = self._game(id_, subtitle, game_data, schedule_data)\n  File \"/home/pi/filefairy/plugin/gameday/gameday.py\", line 406, in _game\n    log_table['body'].append([self._defensive(play)])\n  File \"/home/pi/filefairy/plugin/gameday/gameday.py\", line 312, in _defensive\n    return 'Now {}: {}'.format(_defensive_map[position], player['name'])\nKeyError: 'pitching'",
        "levelname": "INFO",
        "lineno": 127,
        "msg": "Disabled gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:36:54.113782-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:37:19.419055-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:54:53.755589-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:10.513274-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:11.002100-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:11.184329-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:11.268594-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:11.356804-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:11.446027-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:12.612070-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T19:55:12.702287-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T20:08:28.239753-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 104,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T20:13:58.221768-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 312,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T20:13:59.773344-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T20:19:32.257007-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 288,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-06T20:19:32.935539-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:24.223503-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T59'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1945.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:26.102846-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T38'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1947.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:27.876549-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T55'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1955.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:28.577981-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T32'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1951.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:31.123061-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T34'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1946.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:32.881578-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T56'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1953.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 12,
        "date": "2018-11-06T20:21:33.598572-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 246, in parse_game_data\n    curr_fielders = fielders[fielding_team]\nKeyError: 'T51'",
        "levelname": "WARNING",
        "lineno": 352,
        "msg": "Unable to parse https://orangeandblueleaguebaseball.com/StatsLab/reports/news/html/game_logs/log_1952.html.",
        "pathname": "/home/pi/filefairy/util/statslab/statslab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:54:11.618357-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 4,
        "date": "2018-11-06T21:57:04.770854-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:13.482459-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:14.018470-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:14.198333-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:14.311907-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:14.498009-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:14.648215-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:15.821830-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-11-06T21:57:15.936710-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-11-07T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-07T00:00:36.364641-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 8,
        "date": "2018-11-07T07:23:22.847517-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:07:36.874084-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:09.655944-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:24.848219-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.377682-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.562699-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.680364-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.802051-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:25.924268-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:27.108139-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-07T18:08:27.230598-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-11-08T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-08T00:48:27.197797-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:27.742903-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:27.965658-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:28.092711-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:28.223474-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:28.355633-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:29.594560-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T00:48:29.754083-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:35.775267-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.336003-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.565814-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.700007-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:36.914546-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:37.255918-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:38.532455-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T01:12:38.672030-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T18:31:38.055281-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 195,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T19:31:32.884741-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 154,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:00:25.880856-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 104,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:06:59.392510-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 312,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:07:00.865500-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:17:44.050156-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 288,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-08T21:17:44.560671-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-11-09T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-09T00:00:22.374700-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:36.677040-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.234656-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.476879-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.608755-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.741790-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:37.876284-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:40.045357-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T02:17:40.184540-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T03:23:55.194165-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T10:24:00.444320-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T23:28:48.128539-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-09T23:30:08.094690-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      }
    ],
    "2018-11-10T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-10T00:01:02.040908-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:20.351935-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:36.379087-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.046093-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.266980-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.401215-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.544950-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:37.694438-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:38.896202-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T00:07:39.050419-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T15:02:11.848496-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 205,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T17:18:24.379231-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 158,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T18:50:24.828547-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 106,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T18:59:15.184387-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 317,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 2,
        "date": "2018-11-10T19:03:40.543099-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 311,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T19:03:10.813378-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 299,
        "msg": "Download failed.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T19:09:51.567769-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 293,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-10T19:09:52.303934-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 64,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-11-11T00:00:00-08:00": [
      {
        "count": 1,
        "date": "2018-11-11T00:01:06.603804-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 186,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T00:07:35.740615-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 2,
        "date": "2018-11-11T00:44:45.288182-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T03:49:25.606622-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T05:45:41.846195-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T07:13:17.818930-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T07:57:47.639264-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T10:04:38.008024-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T10:36:20.402253-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 2,
        "date": "2018-11-11T11:18:47.013338-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T13:25:42.389400-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T16:41:42.618074-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T17:13:25.841183-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T18:06:26.185629-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T19:15:41.657510-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T21:01:33.543411-08:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 186,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-11T21:22:52.336358-08:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      }
    ]
  }
}
